# Generated by Django 5.2.17 on 2026-09-30 09:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="отчество"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="characters/", verbose_name="фотография"
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="возраст",
                    ),
                ),
                ("bio", models.TextField(verbose_name="биография")),
            ],
            options={
                "verbose_name": "персонаж",
                "verbose_name_plural": "персонажи",
                "ordering": ("last_name", "first_name", "patronymic"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("age__gt", 0)),
                        name="character_age_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="количество голосов"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="votings.character",
                        verbose_name="персонаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "участник",
                "verbose_name_plural": "участники",
                "ordering": (
                    "-vote_count",
                    "character__last_name",
                    "character__first_name",
                ),
            },
        ),
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                ("start_date", models.DateTimeField(verbose_name="дата начала")),
                ("end_date", models.DateTimeField(verbose_name="дата окончания")),
                (
                    "early_finish_votes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Пустое значение отключает досрочное завершение.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="порог досрочного завершения",
                    ),
                ),
                (
                    "characters",
                    models.ManyToManyField(
                        related_name="votings",
                        through="votings.Participation",
                        to="votings.character",
                        verbose_name="персонажи",
                    ),
                ),
            ],
            options={
                "verbose_name": "голосование",
                "verbose_name_plural": "голосования",
                "ordering": ("-start_date", "-pk"),
            },
        ),
        migrations.AddField(
            model_name="participation",
            name="voting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="votings.voting",
                verbose_name="голосование",
            ),
        ),
        migrations.AddConstraint(
            model_name="voting",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="voting_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="voting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("early_finish_votes__isnull", True),
                    ("early_finish_votes__gt", 0),
                    _connector="OR",
                ),
                name="voting_early_finish_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("voting", "character"), name="unique_voting_character"
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.CheckConstraint(
                condition=models.Q(("vote_count__gte", 0)),
                name="participation_vote_count_nonnegative",
            ),
        ),
    ]
